// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpPg3l0u9R2ptMqxwsIaQAWqsVDJTQHrY',
    appId: '1:1055041145910:web:6b073a7fb7e7d6ed489c97',
    messagingSenderId: '1055041145910',
    projectId: 'devcare-hackathon',
    authDomain: 'devcare-hackathon.firebaseapp.com',
    storageBucket: 'devcare-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3J9QlSoD-4Kq8QvdrehKbwsI103auktg',
    appId: '1:1055041145910:android:38f5d849d12cfd57489c97',
    messagingSenderId: '1055041145910',
    projectId: 'devcare-hackathon',
    storageBucket: 'devcare-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpPg3l0u9R2ptMqxwsIaQAWqsVDJTQHrY',
    appId: '1:1055041145910:web:263225e3c51ec1ab489c97',
    messagingSenderId: '1055041145910',
    projectId: 'devcare-hackathon',
    authDomain: 'devcare-hackathon.firebaseapp.com',
    storageBucket: 'devcare-hackathon.firebasestorage.app',
  );
}
